num1=input("enter num:")
num2=input("enter num:")
num3=input("enter num:")
num4=input("enter num:")
num5=input("enter num:")
num6=input("enter num:")
num7=input("enter num:")
num8=input("enter num:")
num9=input("enter num:")
num10=input("enter num:")
num11=input("enter num:")
num12=input("enter num:")
num13=input("enter num:")
num14=input("enter num:")
num15=input("enter num:")
num16=input("enter num:")
num17=input("enter num:")
num18=input("enter num:")
num19=input("enter num:")
num20=input("enter num:")
num21=input("enter num:")
num22=input("enter num:")
num23=input("enter num:")
num24=input("enter num:")
num25=input("enter num:")
num26=input("enter num:")
num27=input("enter num:")
num28=input("enter num:")
num29=input("enter num:")
num30=input("enter num:")
num31=input("enter num:")
num32=input("enter num:")
num33=input("enter num:")
num34=input("enter num:")
num35=input("enter num:")
num36=input("enter num:")
num37=input("enter num:")
num38=input("enter num:")
num39=input("enter num:")
num40=input("enter num:")
num41=input("enter num:")
num42=input("enter num:")
num43=input("enter num:")
num44=input("enter num:")
num45=input("enter num:")
num46=input("enter num:")
num47=input("enter num:")
num48=input("enter num:")
num49=input("enter num:")
num50=input("enter num:")
num51=input("enter num:")
num52=input("enter num:")
num53=input("enter num:")
num54=input("enter num:")
num55=input("enter num:")
num56=input("enter num:")
num57=input("enter num:")
num58=input("enter num:")
num59=input("enter num:")
num60=input("enter num:")

print(num1)
print(num2)
print(num3)
print(num4)
print(num5)
print(num6)
print(num7)
print(num8)
print(num9)
print(num10)
print(num11)
print(num12)
print(num13)
print(num14)
print(num15)
print(num16)
print(num17)
print(num18)
print(num19)
print(num20)
print(num21)
print(num22)
print(num23)
print(num24)
print(num25)
print(num26)
print(num27)
print(num28)
print(num29)
print(num30)
print(num31)
print(num32)
print(num33)
print(num34)
print(num35)
print(num36)
print(num37)
print(num38)
print(num39)
print(num40)
print(num41)
print(num42)
print(num43)
print(num44)
print(num45)
print(num46)
print(num47)
print(num48)
print(num49)
print(num50)
print(num51)
print(num52)
print(num53)
print(num54)
print(num55)
print(num56)
print(num57)
print(num58)
print(num59)
print(num60)